# Generated by Django 2.2.12 on 2021-07-03 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fypapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UseradmitForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'FEMALE'), ('male', 'MALE')], max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=600)),
                ('image', models.ImageField(upload_to=fypapp.models.content_file_name)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item_donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Full_name', models.CharField(max_length=200)),
                ('phoneno', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('shelterhomes', models.CharField(choices=[('Please select shelter home', 'Please select shelter home'), ('Shishu Mandir', 'Shishu Mandir'), ('Adarsha Dala', 'Adarsha Dala'), ('Hasiru Dala', 'Hasiru Dala'), ('Sparsha Trust(Womens)', 'Sparsha Trust(Womens)'), ('Sparsha Trust(Mens)', 'Sparsha Trust(Mens)'), ('Shanti Sayog', 'Shanti Sayog')], default=1, max_length=200)),
                ('items', models.CharField(choices=[('Please select Items you wish to donate', 'Please select Items you wish to donate'), ('CLOTHING', 'CLOTHING'), ('BOOKS', 'BOOKS'), ('FURNITURE', 'FURNITURE'), ('MEDICINES', 'MEDICINES'), ('GROCERY KIT', 'GROCERY KIT'), ('ELECTRONIC GADGET', 'ELECTRONIC GADGET')], default=1, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
